// <auto-generated />
namespace Hotel_Reservation_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RoomIdAddedToReservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomIdAddedToReservation));
        
        string IMigrationMetadata.Id
        {
            get { return "202410301158178_RoomIdAddedToReservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
