// <auto-generated />
namespace Hotel_Reservation_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NumberOfRoomsCreatedToRoomModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberOfRoomsCreatedToRoomModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202411071216488_NumberOfRoomsCreatedToRoomModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
